// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5_Kj4waP2vg2HAjCX9zc-N91SwG5emtM',
    appId: '1:509828808425:web:90f8ab2cd829e999ddfa78',
    messagingSenderId: '509828808425',
    projectId: 'minimalistic-chat',
    authDomain: 'minimalistic-chat.firebaseapp.com',
    storageBucket: 'minimalistic-chat.appspot.com',
    measurementId: 'G-5JVM6L63RV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX_wUc_6jD-w4i9iejCHa6w4Yhh6aJTQo',
    appId: '1:509828808425:android:bb427915bdf52f94ddfa78',
    messagingSenderId: '509828808425',
    projectId: 'minimalistic-chat',
    storageBucket: 'minimalistic-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSK_VGOTN6SHOkF9PTgWiiSFERp2P-KGg',
    appId: '1:509828808425:ios:eb6c77b76f1aa45fddfa78',
    messagingSenderId: '509828808425',
    projectId: 'minimalistic-chat',
    storageBucket: 'minimalistic-chat.appspot.com',
    iosBundleId: 'com.example.minimalisticChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSK_VGOTN6SHOkF9PTgWiiSFERp2P-KGg',
    appId: '1:509828808425:ios:cb92afd0773644d5ddfa78',
    messagingSenderId: '509828808425',
    projectId: 'minimalistic-chat',
    storageBucket: 'minimalistic-chat.appspot.com',
    iosBundleId: 'com.example.minimalisticChat.RunnerTests',
  );
}
